# Plecăm de la imaginea oficială
FROM prom/prometheus:latest

# Copiem fișierul tău de config peste cel default al imaginii
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Expunem portul standard
EXPOSE 9090
